### ISSUE TITLE
Erase action in example does not erase DataFlash block device

### ISSUE THREAD

**Issue by cmonr** [ARMmbed/mbed-os-example-filesystem#23]
Reference https://github.com/ARMmbed/mbed-os-example-filesystem/issues/22 for output and testing parameters.

Erasing and de-initializing the block device do not appear to work.

**Comment by geky** [comment]
Oh huh... The erase function could be a no-op, so maybe we need to actually program 0xffs across the device... Or the dataflash block device could not be erasing correctly.

What happens? Does it print success and then still pick up the filesystem?

**Comment by cmonr** [comment]
@geky Reference the link in the original comment for sample output.

**Comment by kegilbert** [comment]
Reproduced it with IAR on an UBLOX EVK Odin W2 using the DataFlash shield. Everything else ran as expected.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-512

**Comment by davidsaada** [comment]
Example repo uses an old version of the DataFlash driver, which has a bug in the erase API (was fixed since). Will create a PR to use the up to date version.

**Comment by davidsaada** [comment]
Example repo updated with fix.

**Comment by geky** [comment]
Thanks for taking care of this :+1:
