### ISSUE TITLE
documentation: typo in FATfilesystem information

### ISSUE THREAD

**Issue by SamiLappalainenArm** [ARMmbed/mbed-os-example-filesystem#38]
from chapter "Changing the file system":

In Mbed OS, a C++ classes that inherits from the FileSystem interface represents each file system. You can change the file system in the example by changing the class declared in main.cpp.

- LittleFileSystem fs("fs");
+ FATFileSysten fs("fs");

=> FATFileSysten should be FATFileSystem as written in next section inside same chapter.

**Comment by geky** [comment]
Ah good catch
