### ISSUE TITLE
K64F + SPIF + LittleFS using GCC_ARM

### ISSUE THREAD

**Issue by zvikas** [ARMmbed/mbed-os-example-filesystem#48]
Setup: K64F + shield
I didn't modify any code or configuration (using default littlefs with spif)
Got error on boot:
mbed assertation failed: (int)obj->spi.instance != NC, file: .\mbed-os\targets\TARGET_Freescale\TARGET_MCUXpresso_MCUS\TARGET_M”¿“/ÿÿÿÿ
eÐ~

**Comment by zvikas** [comment]
wrong issue

**Comment by zvikas** [comment]
Using K64F with CI Shield 
After modified mbed_lib.json of spif_driver with the following changes:
      "K64F": {
             "SPI_MOSI": "D11",
             "SPI_MISO": "D12",
             "SPI_CLK":  "D13",
             "SPI_CS":   "D10"
        },


I got error :
--- Mbed OS file--- Mbed OS filesystem example ---

Mounting the filesystem... Fail :(

No filesystem found, formatting... Fail :(

error:  (-4001)

**Comment by zvikas** [comment]
I was using wrong CI shield, going to try again with new shield.

**Comment by geky** [comment]
Ah glad you were able to figure out the problem :+1:
