### ISSUE TITLE
[OOB 5.10] Let's use `mbed sterm` instead of serial terminal

### ISSUE THREAD

**Issue by coisme** [ARMmbed/mbed-os-example-filesystem#63]
Hi, this is suggestion for document.

At step 4 in the **Usage > Run the example** section, currently it is described

> Open the UART of the board in your favorite UART viewing program. For example, screen /dev/ttyACM0.

However, now we have `mbed sterm`, can we introduce this cool feature here, in addition to a UART viewing program?

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1603
