### ISSUE TITLE
[OOB 5.10] FATFileSystem examples uses LittleFileSystem

### ISSUE THREAD

**Issue by coisme** [ARMmbed/mbed-os-example-filesystem#66]
The example program in [FATFileSystem reference page](https://os-doc-builder.test.mbed.com/docs/development/apis/fatfilesystem.html#fatfilesystem-example) uses LittleFileSystem.

<img width="1428" alt="screen shot 2018-09-07 at 14 22 06" src="https://user-images.githubusercontent.com/3761826/45200009-c2125a80-b2a9-11e8-914b-1c2bc5086562.png">

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1606

**Comment by ashok-rao** [comment]
@yossi2le @geky .. can you please check this? Thanks.

**Comment by JojoS62** [comment]
I got also confused by LittleFS in FATFS example. Another solution would be a common code with a define as selector, something like this:
```
//
// select filesystem for this example:
// 0: LittleFS, 1: FATFS
//
#define USE_FS=0   
#if (USE_FS == 0)
LittleFileSystem fs;
#elif (USE_FS == 1)
FATFileSystem fs;
#else
#error "specify filesystem by setting USE_FS"
#endif
```

**Comment by geky** [comment]
Although that unfortunately makes the example quite a bit harder to read.

Actually another option would be to embed the documentation about changing filesystems into a big code comment:

``` cpp
// In Mbed OS, a C++ classes that inherits from the FileSystem interface
// represents each file system. You can change the file system in the
// example by changing the class declared here.
// 
// - LittleFileSystem fs("fs");
// + FATFileSystem fs("fs");
// 
// Note: Different file systems require different minimum numbers of storage
// blocks to function. For the FATFileSystem, this example requires a minimum
// of 256 blocks, and for the LittleFileSystem, this example requires a
// minimum of 6 blocks. You can find the number of blocks on a block device
// by dividing the block device's size by its erase size.
//
// FileSystem declaration
LittleFileSystem fs("fs");
```
