### ISSUE TITLE
BUTTON1 not defined for all platforms

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/mbed-os-example-filesystem#76]
This example uses the pin name BUTTON1 in main.cpp.  However, there is no standard that ensures that this name will be defined.  I recommend changing "BUTTON1" to "MBED_CONF_BUTTON1"  or something like that, adding it to the definitions in mbed_app.json file, then allowing target overrides section to define custom definitions for various boards.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-255*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by MarceloSalazar** [comment]
This is being addressed here: https://github.com/ARMmbed/mbed-os/pull/12838
