### ISSUE TITLE
No mention of using NAND flash block devices. 

### ISSUE THREAD

**Issue by peter-tatch** [ARMmbed/mbed-os-example-filesystem#88]
I would like to see some explanation of whether this can work with NAND flash. Can any of the block devices work with raw serial NAND flash? Can we configure the SPIFBlockDevice to work with NAND flash for example. If not, what is the limitation that prevents a NAND block device from being included?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-907*

**Comment by peter-tatch** [comment]
Thank you but that site appears to be down. Is there a new link or is it temporarily down?

**Comment by cmonr** [comment]
@peter-tatch Sorry, but the link is internal-only. It's our way of syncing multiple sources of issue reporting into one collected bucket.

**Comment by dannybenor** [comment]
@peter-tatch NAND is a different technology, that requires the management of bad sectors. It is used in SD cards, therefore the possible way to use NAND in Mbed OS right now is via SD block device

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2069*

**Comment by evedon** [comment]
See further example of changing the block device in https://github.com/ARMmbed/mbed-os-example-blockdevice#changing-the-block-device.

Closing since it seems like this question was answered.
